FROM node:18-alpine

WORKDIR /app

# Copiar archivos de dependencias
COPY frontend/package*.json ./

# Instalar dependencias
RUN npm install --legacy-peer-deps

# Copiar el resto del código (aunque se oculte por el volumen, es buena práctica)
COPY frontend/ .

# Exponer el puerto de Vite
EXPOSE 3000

# Iniciar servidor de desarrollo de Vite
CMD ["npm", "run", "dev"]
