FROM node:18-alpine

WORKDIR /app

# Copiar archivos de dependencias (desde el contexto raíz)
COPY frontend/package*.json ./

# Instalar dependencias
RUN npm install --legacy-peer-deps

# Copiar el resto del código (aunque se oculte por el volumen, es buena práctica)
COPY frontend/ .

# Exponer el puerto por defecto de React
EXPOSE 3000

# Variables de entorno para asegurar hot-reload en Docker
ENV WDS_SOCKET_PORT=0

# Iniciar servidor de desarrollo
CMD ["npm", "start"]
