"""add_chofer_mic_honorario_crt

Revision ID: 2f726eed7325
Revises: ace8ffcbc7fc
Create Date: 2026-01-03 23:56:21.268481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f726eed7325'
down_revision = 'ace8ffcbc7fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('honorarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crt_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'crts', ['crt_id'], ['id'])

    with op.batch_alter_table('mics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chofer', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mics', schema=None) as batch_op:
        batch_op.drop_column('chofer')

    with op.batch_alter_table('honorarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('crt_id')

    # ### end Alembic commands ###
