"""change_mic_campo_40_to_text

Revision ID: 5e2cf697cdf6
Revises: replace_codigo_interno
Create Date: 2026-01-03 03:39:37.704072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e2cf697cdf6'
down_revision = 'replace_codigo_interno'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mics', schema=None) as batch_op:
        batch_op.alter_column('campo_40_tramo',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_roles_assigned_by_fkey'), type_='foreignkey')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('password_changed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('password_changed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('user_roles_assigned_by_fkey'), 'usuarios', ['assigned_by'], ['id'])

    with op.batch_alter_table('mics', schema=None) as batch_op:
        batch_op.alter_column('campo_40_tramo',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
