"""aumentar campo_37 a text

Revision ID: 68e76fe84817
Revises: 8ab6db602497
Create Date: 2026-07-07 01:15:52.664268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e76fe84817'
down_revision = '8ab6db602497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mics', schema=None) as batch_op:
        batch_op.alter_column('campo_37_valor_manual',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mics', schema=None) as batch_op:
        batch_op.alter_column('campo_37_valor_manual',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
