"""add_crt_signature_dates_and_delivery_terms

Revision ID: 6d2d43a0f0d1
Revises: 4915dd8ceb68
Create Date: 2026-07-14 04:17:22.888530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2d43a0f0d1'
down_revision = '4915dd8ceb68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plazo_entrega', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('fecha_firma_remitente', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fecha_firma_transportador', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fecha_firma_destinatario', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crts', schema=None) as batch_op:
        batch_op.drop_column('fecha_firma_destinatario')
        batch_op.drop_column('fecha_firma_transportador')
        batch_op.drop_column('fecha_firma_remitente')
        batch_op.drop_column('plazo_entrega')

    # ### end Alembic commands ###
