"""add_observaciones_to_honorarios

Revision ID: 8ab6db602497
Revises: e20c6e518486
Create Date: 2026-01-13 18:51:43.699321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab6db602497'
down_revision = 'e20c6e518486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('honorarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observaciones', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('honorarios', schema=None) as batch_op:
        batch_op.drop_column('observaciones')

    # ### end Alembic commands ###
