"""add_aduanas_table_final

Revision ID: ace8ffcbc7fc
Revises: 5e2cf697cdf6
Create Date: 2026-01-03 22:24:16.073712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace8ffcbc7fc'
down_revision = '5e2cf697cdf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aduanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('ciudad_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ciudad_id'], ['ciudades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aduanas')
    # ### end Alembic commands ###
