"""add_mic_fields_to_honorario_v2

Revision ID: c51e2ec903d8
Revises: 2f726eed7325
Create Date: 2026-01-04 00:06:36.160328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51e2ec903d8'
down_revision = '2f726eed7325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('honorarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mic_numero', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('chofer', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('placas', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('honorarios', schema=None) as batch_op:
        batch_op.drop_column('placas')
        batch_op.drop_column('chofer')
        batch_op.drop_column('mic_numero')

    # ### end Alembic commands ###
