"""add_tipo_operacion_to_honorarios

Revision ID: e20c6e518486
Revises: c51e2ec903d8
Create Date: 2026-01-13 18:41:01.970159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20c6e518486'
down_revision = 'c51e2ec903d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('honorarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_operacion', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('honorarios', schema=None) as batch_op:
        batch_op.drop_column('tipo_operacion')

    # ### end Alembic commands ###
